name: Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["--geth", "--polygon"]
        node: ["16"]
        include:
          - network: "--geth"
            network-name: geth-localnet
          - network: "--polygon"
            network-name: polygon-localnet

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: nevermined-io/nvm-tools-actions@v0.8.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          opengsn: 'true'
          estuary: 'true'
          contracts-version: 'v3.0.0'
          node-version: 'v1.0.0'
      - name: Install dependencies
        run: |
          yarn
      - name: Run linters
        run: |
          nvm-tools copy-artifacts ./artifacts
          nvm-tools copy-circuits ./circuits
          ls -l ./artifacts
      
      - name: Run integration tests
        env:
          NO_GRAPH: true
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
        run: |
          ls circuits
          yarn test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nevermined-tools-output
          path: tools/nevermined_tools.txt

