name: Tests Nightly

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["--geth"]
        node: ["16"]
        include:
          - network: "--geth"
            network-name: geth-localnet
            chainId: 8998

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: nevermined-io/nvm-tools-actions@v0.12.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          opengsn: 'true'
          estuary: 'true'
          contracts-version: 'v3.2.1'
          node-version: 'v1.2.16'
      - name: Install dependencies
        run: |
          yarn
      - name: Run linters
        run: npm run lint
      - uses: actions/checkout@v3
        with:
          repository: nevermined-io/node
          ref: develop
          path: node
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Build SDK-DTP package and node
        run: |
          yarn build
          yarn pack
          cp *.tgz node/dtp.tgz

          cd node
          sed -i "/sdk-dtp/c\\    \"@nevermined-io/sdk-dtp\": \"./dtp.tgz\"," package.json
          yarn
          yarn run setup:dev
          yarn build

      - name: copy artifacts (network)
        run: |
          nvm-tools copy-artifacts ./artifacts
          nvm-tools copy-circuits ./circuits
          ls -l ./artifacts

      - name: Run node
        run: |
          cd node
          ./scripts/wait-nevermined.sh
          yarn start 2>&1 | tee node_log.txt &
          
          # wait for node
          cd .. 
          ./scripts/wait-service.sh http://localhost:8030

      - name: Run integration tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
          NO_GRAPH: true
        run: |
          yarn test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nevermined-tools-output
          path: tools/nevermined_tools.txt
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: node-output
          path: node-ts/node_log.txt
