name: Testing w/ Nevermined Node depending on SDK changes

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["--geth"]
        node: ["16"]
        include:
          - network: "--geth"
            network-name: geth-localnet
            chainId: 8998

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          yarn
      - name: Run linters
        run: npm run lint
      - uses: actions/checkout@v3
        with:
          repository: nevermined-io/node
          path: node
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Build SDK-DTP package and node
        run: |
          yarn build
          yarn pack
          cp *.tgz node/dtp.tgz

          cd node
          sed -i "/sdk-dtp/c\\    \"@nevermined-io/nevermined-sdk-dtp\": \"./dtp.tgz\"," package.json
          yarn
          yarn run setup:dev
          yarn build

      - name: Run tools (network)
        run: |
          docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
          sudo chmod go+r /etc/hosts
          sudo echo "127.0.0.1  nevermined-metadata" | sudo tee -a /etc/hosts

          # TODO: Use `master` when the renaming is done
          git clone https://github.com/nevermined-io/tools
          cd tools

          export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
          rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"

          ./start_nevermined.sh --latest ${{ matrix.network }} --no-graph --no-node 2>&1 | tee nevermined_tools.txt &
          cd ..
          ./scripts/wait-nevermined.sh

      - name: Run node
        run: |
          cd node
          ./scripts/wait-nevermined.sh
          yarn start 2>&1 | tee node_log.txt &
          
          # wait for node
          cd .. 
          ./scripts/wait-service.sh http://localhost:8030

      - name: Run integration tests
        env:
          SEED_WORDS: ${{ secrets.seedWords }}
          NO_GRAPH: true
        run: |
          yarn test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nevermined-tools-output
          path: tools/nevermined_tools.txt
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: node-output
          path: node-ts/node_log.txt
