name: Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["--geth", "--polygon"]
        node: ["16"]
        include:
          - network: "--geth"
            network-name: geth-localnet
          - network: "--polygon"
            network-name: polygon-localnet

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          yarn
      - name: Run linters
        run: yarn lint
      - name: Run tools (network)
        run: |
          docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
          sudo chmod go+r /etc/hosts
          sudo echo "127.0.0.1  nevermined-metadata" | sudo tee -a /etc/hosts
          git clone https://github.com/nevermined-io/tools
          cd tools

          export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
          rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"

          # TODO: Use the default versions when merged into master
          export KEEPER_VERSION=develop
          export SUBGRAPH_VERSION=develop
          export NODE_VERSION=develop
          ./start_nevermined.sh ${{ matrix.network }} 2>&1 | tee nevermined_tools.txt &
          cd ..
          ./scripts/wait-nevermined.sh
          ./scripts/wait-subgraphs.sh ${{ matrix.network-name }}

          ls circuits

          # wait for marketplace-api
          ./scripts/wait-service.sh http://localhost:3100/api/v1/metadata/assets

      - name: Run integration tests
        env:
          NO_GRAPH: true
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
        run: |
          ls circuits
          yarn test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nevermined-tools-output
          path: tools/nevermined_tools.txt

