name: Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        network: ["--geth", "--polygon"]
        node: ["14"]
        include:
          - network: "--geth"
            network-name: geth-localnet
          - network: "--polygon"
            network-name: polygon-localnet

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Build SDK
        run: |
          git clone https://github.com/nevermined-io/sdk-js
          cd sdk-js
          # git checkout feat/condition-fulfill
          yarn
          yarn build
          yarn pack
          cp *.tgz ..
          cd ..
          rm -rf sdk-js
      - name: Install dependencies
        run: |
          yarn
      - name: Run linters
        run: npm run lint
      - name: Run tools (network)
        run: |
          docker login -u ${{ secrets.NEVERMINED_DOCKER_USERNAME }} -p ${{ secrets.NEVERMINED_DOCKER_TOKEN}}
          sudo chmod go+r /etc/hosts
          sudo echo "127.0.0.1  nevermined-metadata" | sudo tee -a /etc/hosts
          git clone https://github.com/nevermined-io/tools
          cd tools

          export KEEPER_OWNER_ROLE_ADDRESS="0xe2DD09d719Da89e5a3D0F2549c7E24566e947260"
          rm -rf "${HOME}/.nevermined/nevermined-contracts/artifacts"

          # Disabling the compute api for now
          # Check https://github.com/nevermined-io/sdk-js/issues/33

          export KEEPER_VERSION=develop
          ./start_nevermined.sh --latest --no-graph ${{ matrix.network }} 2>&1 | tee nevermined_tools.txt &
          cd ..
          ./scripts/wait-nevermined.sh

      - name: Check artifacts
        run: ls -l node_modules/@nevermined-io/contracts/artifacts

      - name: Run integration tests
        env:
          NO_GRAPH: true
          SEED_WORDS: taxi music thumb unique chat sand crew more leg another off lamp
        run: |
          yarn test || yarn test || yarn test || yarn test || yarn test || yarn test || yarn test || yarn test || yarn test || yarn test || yarn test
      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nevermined-tools-output
          path: tools/nevermined_tools.txt

